language: go

go:
 - 1.7
 - 1.8

install:
 - go get -v -u github.com/golang/lint/golint
 - go get -v -u github.com/mattn/goveralls
 - go get -v -u github.com/stretchr/testify/...

script:
 - golint -set_exit_status ./...
 - go vet ./...
 - go test -v -covermode=count -coverprofile=profile.cov ./
 - go test -v -covermode=count -coverprofile=profile-internal.cov.part ./internal

after_success:
 - "grep -h -v \"mode: count\" *.cov.part >> profile.cov"
 - goveralls -coverprofile=profile.cov -service=travis-ci
